# Generated by Django 3.0.8 on 2020-07-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maids', '0003_auto_20200718_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maid',
            options={},
        ),
        migrations.RemoveField(
            model_name='maid',
            name='created',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='modified',
        ),
    ]
